version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: sgse_db
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - sgse-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  eureka-server:
    image: leweeskys/eureka-server:latest
    container_name: eureka-server
    ports:
      - "8762:8762"
    networks:
      - sgse-network

  api-gateway:
    image: leweeskys/api-gateway:latest
    container_name: api-gateway
    ports:
      - "9090:9090"
    depends_on:
      - eureka-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8762/eureka
    networks:
      - sgse-network

  encadreur-service:
    image: leweeskys/encadreur-service:latest
    container_name: encadreur-service
    ports:
      - "9092:9092"
    depends_on:
      - eureka-server
      - mysql
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8762/eureka
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/sgse_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=dev
      - SPRING_DATASOURCE_PASSWORD=dev
    restart: on-failure
    networks:
      - sgse-network

  stagiaire-service:
    image: leweeskys/stagiaire-service:latest
    container_name: stagiaire-service
    ports:
      - "9091:9091"
    depends_on:
      - eureka-server
      - mysql
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8762/eureka
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/sgse_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=dev
      - SPRING_DATASOURCE_PASSWORD=dev
    restart: on-failure
    networks:
      - sgse-network

networks:
  sgse-network:
    driver: bridge
