services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: sgse_db
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
    ports:
      - "3308:3306"
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - sgse-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  eureka-server:
    build:
      context: ./eureka-server/
      dockerfile: Dockerfile
    container_name: eureka-server
    image: sbore669/eureka-server
    ports:
      - "8762:8762"
    networks:
      - sgse-network

  api-gateway:
    build:
      context: ./gateway/
      dockerfile: Dockerfile
    container_name: api-gateway
    image: sbore669/api-gateway
    ports:
      - "9090:9090"
    depends_on:
      - eureka-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8762/eureka
    networks:
      - sgse-network

  encadreur-service:
    build:
      context: ./encadreur-service/
      dockerfile: Dockerfile
    container_name: encadreur-service
    image: sbore669/encadreur-service
    ports:
      - "9092:9092"
    depends_on:
      - eureka-server
      - mysql
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8762/eureka
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/sgse_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=dev
      - SPRING_DATASOURCE_PASSWORD=dev
    restart: on-failure
    networks:
      - sgse-network

  stagiaire-service:
    build:
      context: ./stagiaire-service/
      dockerfile: Dockerfile
    container_name: stagiaire-service
    image: sbore669/stagiaire-service
    ports:
      - "9091:9091"
    depends_on:
      - eureka-server
      - mysql
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8762/eureka
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/sgse_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=dev
      - SPRING_DATASOURCE_PASSWORD=dev
    restart: on-failure
    networks:
      - sgse-network

networks:
  sgse-network:
    driver: bridge
